- name : Configuring the shipping server
  hosts : shipping
  become : yes

  tasks :
  - name : Install maven
    package :
      name : "{{ item }}"
      state : present
    loop :
    - maven
    - mysql
  
  - name : create roboshop system user
    user :
      name : roboshop
      system : true 
      home : /app
      shell: /sbin/nologin
      comment: "roboshop system user"

  - name : remove app directory
    file :
      path: /app
      state: absent

  - name : Delete shipping.zip file in the tmp directory
    file :
      path: /tmp/shipping.zip
      state: absent

  - name : create app directory
    file :
      path: /app
      state: directory
      owner : roboshop
      group : roboshop

  - name : Download shipping 
    get_url:
       url:  https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
       dest: /tmp/shipping.zip

  - name : unzip shipping
    unarchive:
      src : /tmp/shipping.zip
      dest : /app
      remote_src: yes

  - name: Fix extracted files permissions
    ansible.builtin.file:
      path: /app
      owner: roboshop
      group: roboshop
      recurse: yes

  - name: Install dependencies
    command : mvn clean package
    args : 
      chdir: /app 
    
  - name : move shipping jar
    command : mv target/shipping-1.0.jar shipping.jar 
    args : 
      chdir : /app

  - name : copy shipping.service
    template :
      src: shipping.service.j2
      dest: /etc/systemd/system/shipping.service
      
    
  - name : Install PyMySQL
    pip:
      name: PyMySQL
      executable: pip3.9

  - name : Load mysql data
    community.mysql.mysql_db:
      state: import
      name: all
      login_user : root
      login_password : Roboshop@1
      login_host : mysql.dinakardevops.online
      target : "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql
    tags : load
  
  - name : daemon reload ,start , enable shipping
    systemd_service:
      name : shipping
      state : restarted
      enabled : yes
      daemon_reload : true


      
      