[local]
localhost

[mongodb]
mongodb.dinakardevops.online

[redis]
redis.dinakardevops.online

[mysql]
mysql.dinakardevops.online

[user]
user.dinakardevops.online

[cart]
cart.dinakardevops.online

[rabbitmq]
rabbitmq.dinakardevops.online

[catalogue]
catalogue.dinakardevops.online

[frontend]
dinakardevops.online